name: sydtest-playground
version: 0.1.0.0
github: "L7R7/sydtest-playground"
license: BSD3
author: "Leonhard Riedißer"
maintainer: "leo008180@googlemail.com"
copyright: "2023 Leonhard Riedißer"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/L7R7/sydtest-playground#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

tests:
  sydtest-playground-test:
    main: Main.hs
    source-dirs: test
    build-tools: sydtest-discover >= 0.0.0.3
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - sydtest
