resolver: lts-18.28
packages:
  - .

extra-deps:
  - sydtest-0.9.0.0@sha256:1d3f5d824176fbccc8a4812871fed61a871a1e86f516d00947532ac118c496e7,3714
  - sydtest-wai-0.2.0.0@sha256:f73bb6e2375f0e588cc7e245052fa8d99dd9f9be57f424efc133185cf64474a9,1620
  - github: NorfairKing/safe-coloured-text
    commit: 95860cbf6aa7c50d9c3702165bf6df25baf770b1
    subdirs:
      - safe-coloured-text
      - safe-coloured-text-terminfo
  - github: NorfairKing/autodocodec
    commit: de3a6efbfad165d2265f9d222a570d9a938c162d
    subdirs:
      - autodocodec
      - autodocodec-schema
      - autodocodec-yaml
  - github: NorfairKing/validity
    commit: 160e846cc5de8e92e6758172da341f5d81fe0374
    subdirs:
      - validity
      - validity-aeson
      - validity-bytestring
      - validity-containers
      - validity-scientific
      - validity-text
      - validity-unordered-containers
      - validity-vector
