name: Build

on: push

jobs:
  build-all:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/stack.yaml.lock','**/polysemy-servant.cabal') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-

      - uses: haskell-actions/setup@v2.7.7
        with:
          ghc-version: '8.10.7'
          enable-stack: true
          stack-version: '2.15.1'

      - name: Build polysemy-servant
        working-directory: ./polysemy-servant
        run: |
          stack build --system-ghc --test --coverage --copy-bins --local-bin-path .

      - name: Build sydtest-playground
        working-directory: ./sydtest-playground
        run: |
          stack build --system-ghc --test --coverage --copy-bins --local-bin-path .

      - name: Build form-validation-experiments
        working-directory: ./form-validation-experiments
        run: |
          stack build --system-ghc --test --coverage --copy-bins --local-bin-path .

      - name: Build servant-type-roles
        working-directory: ./servant-type-roles
        run: |
          stack build --system-ghc --test --coverage --copy-bins --local-bin-path .

      - name: Build servant-paginated-client
        working-directory: ./servant-paginated-client
        run: |
          stack build --system-ghc --test --coverage --copy-bins --local-bin-path .

