name: Build

on: push

jobs:
  build-polysemy-servant:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/stack.yaml.lock','**/polysemy-servant.cabal') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-

      - uses: haskell/actions/setup@v2.0.3
        with:
          ghc-version: '8.10.7'
          enable-stack: true
          stack-version: '2.7.1'

      - name: Build executable
        working-directory: ./polysemy-servant
        run: |
          stack build --system-ghc --test --coverage --copy-bins --local-bin-path .
